package com.example.shopmall.shopmall1710a.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.shopmall.shopmall1710a.greenDao.ShopMessage;

import com.example.shopmall.shopmall1710a.greenDao.ShopMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopMessageDaoConfig;

    private final ShopMessageDao shopMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopMessageDaoConfig = daoConfigMap.get(ShopMessageDao.class).clone();
        shopMessageDaoConfig.initIdentityScope(type);

        shopMessageDao = new ShopMessageDao(shopMessageDaoConfig, this);

        registerDao(ShopMessage.class, shopMessageDao);
    }
    
    public void clear() {
        shopMessageDaoConfig.clearIdentityScope();
    }

    public ShopMessageDao getShopMessageDao() {
        return shopMessageDao;
    }

}
